version: "3"
networks:
  expense:
volumes:
  mysql: # docker volume create mysql
services:
  mysql:
    image: avkdocr/mysql:v1
    container_name: mysql
    volumes:
      -mysql:/var/lib/mysql
  backend:
    image: avkdocr/backend:v1
    container_name: backend
    depends_on:
      - mysql
  frontend:
    image: avkdocr/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend

